---
title: "Lab_1: Fix data and Get ID"
author: "Elizaveta Grishina"
date: "25 09 2021"
output: 
  html_document:
    df_print: kable
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fix data

#### Below there are functions, which realize the main function fix_data

```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}

    get_data <- function(filename) {
      data <- read.csv(filename) 
    }
```

Remove spaces in necessary cells.

```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}
    remove_space <- function(col){
    fixed_col <- gsub(" ", "", col, fixed = TRUE) 
    num_col <- as.numeric(fixed_col) 
    
    if (any(is.na(num_col)))
      return(col) 
    else
      return(num_col)
  }
```

Final function

```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}
    fix_data <- function(data, work_func)
      return(sapply(data, remove_space))
```

#### Final program

```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}

  data <- get_data('test_data_01.csv') 
  print(fix_data(data, remove_space))
```

## Get ID

```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, include=TRUE}
merge_data <- function(data){ 
    counter = 2 
    new_data = merge(data[1], data[2], by='id', all=TRUE, suffixes = c(".1",".2"))
    while (counter < 7){
      new_data = merge(new_data, data[counter], by='id', all=TRUE, 
                       suffixes = c(paste0(".", counter),paste0(".", counter + 1)))
      counter = counter + 1
    }
    return(new_data) 
  }

  get_id <- function(data) { 
    new_data = merge_data(data) 
    new_data = na.omit(new_data) 
    data_without_id <- new_data[, -c(1)] 
    means = rowMeans(data_without_id) 
    return(data.frame(id=new_data$id, mean_temp=means)) 
  }
```

```{r echo=TRUE, results='asis',error=FALSE,warning=FALSE, include=TRUE}
load('data.RData')
ids = get_id(data)
ids
```
